const vendorCategories = [
  "Photography & Videography",
  "Catering & Food",
  "Decoration & Flowers",
  "Music & Entertainment",
  "Transportation",
  "Beauty & Makeup",
  "Wedding Planning",
  "Venue Management",
  "Jewelry & Accessories",
  "Wedding Attire",
];

const subCategories = {
  "Photography & Videography": [
    "Wedding Photography",
    "Engagement Photography",
    "Pre-wedding Shoot",
    "Wedding Videography",
    "Cinematography",
    "Photo Editing",
  ],
  "Catering & Food": [
    "Wedding Catering",
    "Reception Catering",
    "Traditional Food",
    "International Cuisine",
    "Desserts & Cakes",
    "Beverages",
  ],
  "Decoration & Flowers": [
    "Wedding Decoration",
    "Flower Arrangements",
    "Stage Decoration",
    "Mandap Decoration",
    "Reception Decoration",
    "Lighting",
  ],
  "Music & Entertainment": [
    "Live Music",
    "DJ Services",
    "Traditional Music",
    "Dance Performances",
    "Sound System",
    "Entertainment Shows",
  ],
  Transportation: [
    "Wedding Car",
    "Guest Transportation",
    "Bridal Car",
    "Luxury Cars",
    "Bus Services",
    "Airport Transfer",
  ],
  "Beauty & Makeup": [
    "Bridal Makeup",
    "Groom Makeup",
    "Hair Styling",
    "Mehendi Services",
    "Spa Services",
    "Beauty Treatments",
  ],
  "Wedding Planning": [
    "Full Wedding Planning",
    "Partial Planning",
    "Destination Wedding",
    "Wedding Coordination",
    "Budget Planning",
    "Vendor Management",
  ],
  "Venue Management": [
    "Wedding Venues",
    "Reception Venues",
    "Outdoor Venues",
    "Indoor Venues",
    "Destination Venues",
    "Banquet Halls",
  ],
  "Jewelry & Accessories": [
    "Bridal Jewelry",
    "Groom Jewelry",
    "Wedding Rings",
    "Traditional Jewelry",
    "Modern Jewelry",
    "Accessories",
  ],
  "Wedding Attire": [
    "Bridal Lehenga",
    "Groom Sherwani",
    "Wedding Sarees",
    "Designer Wear",
    "Traditional Attire",
    "Modern Attire",
  ],
};
